# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='avec',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default='email@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='freshman_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='greeting',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='is_invited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='menu_type',
            field=models.CharField(default='with alcohol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='sillis',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='special_diet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='table_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_type',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
