# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171017_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='avec',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
