# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171017_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='freshman_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='special_diet',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
