# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20171018_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='greeting_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
